module.exports = {
  apps: [
    {
      name: 'p1-fixed-industry_concept_analysis_fixed',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_industry_concept_analysis_fixed.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p1-fixed-industry_concept_analysis_fixed-error.log',
      out_file: '/var/log/pm2/p1-fixed-industry_concept_analysis_fixed-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p1-fixed-technical_analysis_fixed',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_technical_analysis_fixed.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p1-fixed-technical_analysis_fixed-error.log',
      out_file: '/var/log/pm2/p1-fixed-technical_analysis_fixed-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p1-fixed-stock_detail_fixed',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_stock_detail_fixed.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p1-fixed-stock_detail_fixed-error.log',
      out_file: '/var/log/pm2/p1-fixed-stock_detail_fixed-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p1-fixed-settings_fixed',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_settings_fixed.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p1-fixed-settings_fixed-error.log',
      out_file: '/var/log/pm2/p1-fixed-settings_fixed-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p1-fixed-trade_management_fixed',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_trade_management_fixed.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p1-fixed-trade_management_fixed-error.log',
      out_file: '/var/log/pm2/p1-fixed-trade_management_fixed-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p1-fixed-risk_monitor_fixed',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_risk_monitor_fixed.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p1-fixed-risk_monitor_fixed-error.log',
      out_file: '/var/log/pm2/p1-fixed-risk_monitor_fixed-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p1-fixed-real_time_monitor_fixed',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_real_time_monitor_fixed.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p1-fixed-real_time_monitor_fixed-error.log',
      out_file: '/var/log/pm2/p1-fixed-real_time_monitor_fixed-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p1-fixed-market_fixed',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_market_fixed.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p1-fixed-market_fixed-error.log',
      out_file: '/var/log/pm2/p1-fixed-market_fixed-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    }
  ]
}
