module.exports = {
  apps: [
    {
      name: 'p2-indicator_library',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_indicator_library_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-indicator_library-error.log',
      out_file: '/var/log/pm2/p2-indicator_library-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-task_management',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_task_management_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-task_management-error.log',
      out_file: '/var/log/pm2/p2-task_management-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-openstock_demo',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_openstock_demo_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-openstock_demo-error.log',
      out_file: '/var/log/pm2/p2-openstock_demo-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-pyprofiling_demo',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_pyprofiling_demo_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-pyprofiling_demo-error.log',
      out_file: '/var/log/pm2/p2-pyprofiling_demo-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-freqtrade_demo',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_freqtrade_demo_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-freqtrade_demo-error.log',
      out_file: '/var/log/pm2/p2-freqtrade_demo-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-stock_analysis_demo',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_stock_analysis_demo_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-stock_analysis_demo-error.log',
      out_file: '/var/log/pm2/p2-stock_analysis_demo-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-tdxpy_demo',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_tdxpy_demo_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-tdxpy_demo-error.log',
      out_file: '/var/log/pm2/p2-tdxpy_demo-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-smart_data_source_test',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_smart_data_source_test_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-smart_data_source_test-error.log',
      out_file: '/var/log/pm2/p2-smart_data_source_test-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-tdx_market',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_tdx_market_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-tdx_market-error.log',
      out_file: '/var/log/pm2/p2-tdx_market-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-fund_flow',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_fund_flow_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-fund_flow-error.log',
      out_file: '/var/log/pm2/p2-fund_flow-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-etf_data',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_etf_data_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-etf_data-error.log',
      out_file: '/var/log/pm2/p2-etf_data-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-chip_race',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_chip_race_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-chip_race-error.log',
      out_file: '/var/log/pm2/p2-chip_race-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-longhubang',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_longhubang_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-longhubang-error.log',
      out_file: '/var/log/pm2/p2-longhubang-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p2-wencai',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_wencai_p2.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p2-wencai-error.log',
      out_file: '/var/log/pm2/p2-wencai-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
  ]
};
