#!/usr/bin/env python3
"""
TDengine 标签迁移脚本

目的：为所有TDengine超级表添加用于Saga事务控制的Tags。
Tags:
- txn_id: BINARY(64) - 事务ID
- is_valid: BOOL - 数据有效性标记
"""

import os
import sys
import yaml
import logging
from typing import Dict, List, Any

# 设置日志
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# 配置路径
CONFIG_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), 'config', 'table_config.yaml')

def load_config() -> Dict[str, Any]:
    try:
        with open(CONFIG_PATH, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        logger.error(f"Config file not found: {CONFIG_PATH}")
        sys.exit(1)

def get_tdengine_stables(config: Dict[str, Any]) -> List[str]:
    stables = []
    tables = config.get('tables', [])
    for table in tables:
        if table.get('database_type') == 'TDengine' and table.get('is_super_table'):
            db_name = table.get('database_name')
            tb_name = table.get('table_name')
            stables.append(f"{db_name}.{tb_name}")
    return stables

def generate_migration_sql(stables: List[str]):
    print("-- TDengine Migration SQL Script")
    print("-- Generated by migrate_tdengine_tags.py")
    print("-- Execute these commands in TDengine CLI (taos)")
    print("")

    for stable in stables:
        print(f"-- Adding tags for {stable}")
        # TDengine Syntax: ALTER STABLE <stable_name> ADD TAG <tag_name> <tag_type>;
        # Note: TDengine 3.0+ syntax might vary slightly, assuming standard SQL
        print(f"ALTER STABLE {stable} ADD TAG txn_id BINARY(64);")
        print(f"ALTER STABLE {stable} ADD TAG is_valid BOOL;")
        print("")

    print("-- Migration Script End")

if __name__ == "__main__":
    logger.info("Starting TDengine Tag Migration Generator")
    config = load_config()
    stables = get_tdengine_stables(config)

    if not stables:
        logger.warning("No TDengine super tables found in config.")
        sys.exit(0)

    logger.info(f"Found {len(stables)} TDengine super tables.")
    generate_migration_sql(stables)
    logger.info("SQL generation complete.")
