const path = require("node:path");

const projectRoot = path.resolve(__dirname, "..", "..");
const backendCwd = path.join(projectRoot, "web", "backend");
const frontendCwd = path.join(projectRoot, "web", "frontend");
const prodLogDir = process.env.MYSTOCKS_LOG_DIR || "/opt/mystocks/logs";

const frontendPort = process.env.FRONTEND_PORT || "3020";
const backendPort = process.env.BACKEND_PORT || "8020";
const backendBackupPort = process.env.BACKEND_BACKUP_PORT || "8021";
const pythonBin = process.env.PYTHON_BIN || "/root/miniconda3/envs/stock/bin/python";
const nodeBin = process.env.NODE_BIN || "npx";

module.exports = {
  apps: [
    {
      name: "mystocks-backend",
      script: pythonBin,
      args: `-m uvicorn app.main:app --host 0.0.0.0 --port ${backendPort} --workers 4`,
      cwd: backendCwd,
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        USE_MOCK: "false",
        USE_MOCK_DATA: "false",
        ENVIRONMENT: "production",
        PYTHONPATH: `${backendCwd}:${projectRoot}`,
        LOG_LEVEL: process.env.LOG_LEVEL || "info",
        BACKEND_PORT: backendPort,
        BACKEND_BACKUP_PORT: backendBackupPort,
        PORT: backendPort,
        port: backendPort,
        PORT_RANGE_END: backendBackupPort,
        port_range_end: backendBackupPort,
      },
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
      min_uptime: "10s",
      max_memory_restart: "1G",
      node_args: "--max-old-space-size=1024",
      health_check: {
        enable: true,
        url: `http://localhost:${backendPort}/api/monitoring/health`,
        interval: 30000,
        max_retries: 3,
        timeout: 5000,
      },
      log_file: path.join(prodLogDir, "backend.log"),
      out_file: path.join(prodLogDir, "backend-out.log"),
      error_file: path.join(prodLogDir, "backend-error.log"),
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 5000,
    },
    {
      name: "mystocks-frontend",
      script: nodeBin,
      args: `serve ${path.join(frontendCwd, "dist")} -l ${frontendPort} -s`,
      cwd: projectRoot,
      instances: 1,
      exec_mode: "fork",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
        PORT: frontendPort,
        FRONTEND_PORT: frontendPort,
      },
      autorestart: true,
      watch: false,
      max_restarts: 5,
      restart_delay: 3000,
      min_uptime: "5s",
      max_memory_restart: "512M",
      health_check: {
        enable: true,
        url: `http://localhost:${frontendPort}`,
        interval: 30000,
        max_retries: 2,
        timeout: 3000,
      },
      log_file: path.join(prodLogDir, "frontend.log"),
      out_file: path.join(prodLogDir, "frontend-out.log"),
      error_file: path.join(prodLogDir, "frontend-error.log"),
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_timeout: 3000,
    },
    {
      name: "data-sync-basic",
      script: pythonBin,
      args: "scripts/data_sync/sync_stock_basic.py",
      cwd: projectRoot,
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        ENVIRONMENT: "production",
        PYTHONPATH: projectRoot,
      },
      cron_restart: "0 3 * * 0",
      autorestart: true,
      watch: false,
      max_restarts: 3,
      restart_delay: 10000,
      max_memory_restart: "512M",
      out_file: path.join(prodLogDir, "data-sync-basic.log"),
      error_file: path.join(prodLogDir, "data-sync-basic-error.log"),
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      kill_timeout: 10000,
    },
    {
      name: "data-sync-kline",
      script: pythonBin,
      args: "scripts/data_sync/sync_stock_kline.py",
      cwd: projectRoot,
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        ENVIRONMENT: "production",
        PYTHONPATH: projectRoot,
      },
      cron_restart: "0 2 * * *",
      autorestart: true,
      watch: false,
      max_restarts: 3,
      restart_delay: 10000,
      max_memory_restart: "512M",
      out_file: path.join(prodLogDir, "data-sync-kline.log"),
      error_file: path.join(prodLogDir, "data-sync-kline-error.log"),
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      kill_timeout: 10000,
    },
    {
      name: "data-sync-minute-kline",
      script: pythonBin,
      args: "scripts/data_sync/sync_minute_kline.py --periods 1m 5m 15m 30m 60m",
      cwd: projectRoot,
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        ENVIRONMENT: "production",
        PYTHONPATH: projectRoot,
      },
      cron_restart: "0 17 * * 1-5",
      autorestart: true,
      watch: false,
      max_restarts: 3,
      restart_delay: 10000,
      max_memory_restart: "512M",
      out_file: path.join(prodLogDir, "data-sync-minute-kline.log"),
      error_file: path.join(prodLogDir, "data-sync-minute-kline-error.log"),
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      kill_timeout: 10000,
    },
    {
      name: "data-sync-industry-classify",
      script: pythonBin,
      args: "scripts/data_sync/sync_industry_classify.py",
      cwd: projectRoot,
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        ENVIRONMENT: "production",
        PYTHONPATH: projectRoot,
      },
      cron_restart: "0 4 * * 1",
      autorestart: true,
      watch: false,
      max_restarts: 3,
      restart_delay: 10000,
      max_memory_restart: "256M",
      out_file: path.join(prodLogDir, "data-sync-industry.log"),
      error_file: path.join(prodLogDir, "data-sync-industry-error.log"),
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      kill_timeout: 10000,
    },
    {
      name: "data-sync-concept-classify",
      script: pythonBin,
      args: "scripts/data_sync/sync_concept_classify.py",
      cwd: projectRoot,
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        ENVIRONMENT: "production",
        PYTHONPATH: projectRoot,
      },
      cron_restart: "30 4 * * 1",
      autorestart: true,
      watch: false,
      max_restarts: 3,
      restart_delay: 10000,
      max_memory_restart: "256M",
      out_file: path.join(prodLogDir, "data-sync-concept.log"),
      error_file: path.join(prodLogDir, "data-sync-concept-error.log"),
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      kill_timeout: 10000,
    },
    {
      name: "system-monitor",
      script: pythonBin,
      args: "src/monitoring/performance_monitor.py",
      cwd: projectRoot,
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        ENVIRONMENT: "production",
        PYTHONPATH: projectRoot,
      },
      autorestart: true,
      watch: false,
      max_restarts: 5,
      restart_delay: 5000,
      max_memory_restart: "256M",
      out_file: path.join(prodLogDir, "system-monitor.log"),
      error_file: path.join(prodLogDir, "system-monitor-error.log"),
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      kill_timeout: 5000,
    },
  ],
  deploy: {
    production: {
      user: "mystocks",
      host: ["your-production-server.com"],
      ref: "origin/main",
      repo: "git@github.com:your-org/mystocks.git",
      path: "/opt/mystocks",
      "post-deploy":
        "npm install && pip install -r requirements.txt && npm run build && pm2 reload config/pm2/ecosystem.production.config.js --env production",
      "pre-setup": "apt update && apt install -y python3 python3-pip nodejs npm postgresql postgresql-contrib redis-server",
    },
  },
};
