module.exports = {
  apps: [
    {
      name: 'p0-dashboard',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_dashboard_p0.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p0-dashboard-error.log',
      out_file: '/var/log/pm2/p0-dashboard-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p0-market',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_market_p0.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p0-market-error.log',
      out_file: '/var/log/pm2/p0-market-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p0-stocks',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_stocks_p0.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p0-stocks-error.log',
      out_file: '/var/log/pm2/p0-stocks-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p0-analysis',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_analysis_p0.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p0-analysis-error.log',
      out_file: '/var/log/pm2/p0-analysis-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p0-trade',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_trade_p0.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p0-trade-error.log',
      out_file: '/var/log/pm2/p0-trade-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
    {
      name: 'p0-settings',
      script: '/root/miniconda3/envs/stock/bin/python',
      args: '/tmp/test_settings_p0.py',
      interpreter: 'none',
      cwd: '/opt/claude/mystocks_spec',
      error_file: '/var/log/pm2/p0-settings-error.log',
      out_file: '/var/log/pm2/p0-settings-out.log',
      env: {
        PYTHONUNBUFFERED: '1',
        PLAYWRIGHT_BROWSERS_PATH: '/root/.cache/ms-playwright',
      },
      autorestart: false,
      max_memory_restart: '500M',
    },
  ]
};
