import { describe, expect, it } from 'vitest'

import { stripTsNoCheckFromGeneratedDts } from '../../../scripts/dev/normalize-generated-dts.mjs'

describe('normalize generated dts', () => {
  it('removes the generated ts-nocheck directive while keeping the rest of the file intact', () => {
    const source = [
      '/* eslint-disable */',
      '// @ts-nocheck',
      '// Generated by unplugin-vue-components',
      'export {}',
      '',
    ].join('\n')

    expect(stripTsNoCheckFromGeneratedDts(source)).toBe([
      '/* eslint-disable */',
      '// Generated by unplugin-vue-components',
      'export {}',
      '',
    ].join('\n'))
  })
})
