/**
 * API 契约类型定义
 *
 * 遵循项目的API契约管理规范：
 * - Contract First Development
 * - Schema First Architecture  
 * - OpenAPI 3.0 规范
 *
 * 注意：大部分API类型已通过后端Pydantic模型自动生成
 * 位置: web/frontend/src/api/types/generated-types.ts
 *
 * 此文件仅包含前端特有的API辅助类型定义
 */

// ============================================
// API 响应包装器 (符合契约规范)
// ============================================

/**
 * 统一API响应格式
 * 符合后端契约管理平台的响应规范
 */
export interface UnifiedResponse<TData = any> {
  code: string | number        // 响应码 (SUCCESS, ERROR等)
  message: string              // 响应消息
  data: TData                  // 响应数据
  request_id?: string          // 请求ID (用于追踪)
  timestamp?: number | string  // 响应时间戳
}

/**
 * 分页响应数据
 */
export interface PaginatedData<T> {
  items: T[]                   // 数据项列表
  total: number                // 总数
  page: number                 // 当前页码
  pageSize: number             // 每页大小
  totalPages: number           // 总页数
}

/**
 * 分页API响应
 */
export type PaginatedResponse<T> = UnifiedResponse<PaginatedData<T>>

// ============================================
// API 错误类型 (符合契约错误码规范)
// ============================================

/**
 * API 错误响应
 */
export interface APIError {
  code: string                 // 错误码 (如: CONTRACT_VERSION_NOT_FOUND)
  message: string              // 错误消息
  details?: any                // 错误详情
  timestamp?: number           // 错误时间戳
}

/**
 * 错误码枚举 (来自契约管理平台)
 */
export enum ErrorCode {
  // 通用错误
  SUCCESS = 'SUCCESS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  
  // 契约管理专属错误
  CONTRACT_VERSION_NOT_FOUND = 'CONTRACT_VERSION_NOT_FOUND',
  CONTRACT_NOT_FOUND = 'CONTRACT_NOT_FOUND',
  CONTRACT_ALREADY_EXISTS = 'CONTRACT_ALREADY_EXISTS',
  CONTRACT_VALIDATION_FAILED = 'CONTRACT_VALIDATION_FAILED',
  CONTRACT_DELETE_ACTIVE_VERSION = 'CONTRACT_DELETE_ACTIVE_VERSION',
  CONTRACT_DIFF_FAILED = 'CONTRACT_DIFF_FAILED',
  CONTRACT_SYNC_FAILED = 'CONTRACT_SYNC_FAILED'
}

// ============================================
// HTTP 方法和配置
// ============================================

/**
 * HTTP 方法类型
 */
export type HTTPMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'

/**
 * API 请求配置
 */
export interface APIRequestConfig {
  timeout?: number            // 请求超时时间 (毫秒)
  retries?: number            // 重试次数
  cache?: boolean             // 是否使用缓存
  cacheTTL?: number           // 缓存有效期 (毫秒)
  headers?: Record<string, string>  // 自定义请求头
}

/**
 * API 端点配置
 */
export interface APIEndpoint {
  url: string                 // 端点URL
  method: HTTPMethod          // HTTP方法
  params?: Record<string, any>     // 查询参数
  data?: Record<string, any>       // 请求体数据
  config?: APIRequestConfig  // 请求配置
}

// ============================================
// WebSocket 类型 (实时通信)
// ============================================

/**
 * WebSocket 消息类型
 */
export type WSMessageType =
  | 'market.quote'       // 实时行情更新
  | 'market.kline'       // K线数据更新
  | 'trade.signal'       // 交易信号通知
  | 'system.alert'       // 系统告警
  | 'ping'              // 心跳ping
  | 'pong'              // 心跳pong

/**
 * WebSocket 消息结构
 */
export interface WSMessage<T = any> {
  type: WSMessageType
  data: T
  timestamp?: number
}

/**
 * 市场行情更新消息
 */
export interface MarketQuoteUpdate {
  symbol: string
  price: number
  change: number
  changePercent: number
  volume: number
  timestamp: number
}

// ============================================
// 导入自动生成的类型
// ============================================

// 重新导出生成类型，提供统一的导入入口
// 实际类型定义位于: web/frontend/src/api/types/generated-types.ts
export type {
  UnifiedResponse as AutoGeneratedUnifiedResponse,
  AccountInfo,
  AlertRecordResponse,
  AddWatchlistRequest
} from '@/api/types/generated-types'
