/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/market/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取市场概览
         * @description 获取A股市场整体概览数据，包括：
         *     - 主要市场指数（上证指数、深证成指等）
         *     - 市场涨跌统计
         *     - 换手率
         *     - 涨幅榜前N名ETF
         */
        get: operations["getMarketOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/fund-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询资金流向
         * @description 查询指定股票的资金流向数据，包括：
         *     - 主力资金流向
         *     - 散户资金流向
         *     - 大单资金流向
         */
        get: operations["getFundFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/kline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取K线数据
         * @description 获取指定股票的K线数据，支持：
         *     - 分钟K：1m, 5m, 15m, 30m
         *     - 小时K：1h
         *     - 日K：1d
         */
        get: operations["getKlineData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/etf/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询ETF列表
         * @description 查询ETF列表，支持多种筛选条件：
         *     - 按代码或名称搜索
         *     - 按市场筛选（上海/深圳）
         *     - 按类型筛选（股票/债券/商品/货币/QDII）
         */
        get: operations["getETFList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/lhb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询龙虎榜数据
         * @description 查询指定日期的龙虎榜数据，包括：
         *     - 涨幅榜上榜股票
         *     - 跌幅榜上榜股票
         *     - 异常波动股票
         */
        get: operations["getLongHuBang"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/chip-race": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询竞价抢筹数据
         * @description 查询指定日期的竞价抢筹数据，包括：
         *     - 开盘抢筹比例
         *     - 主力vs散户买入对比
         *     - 热门抢筹股票排行
         */
        get: operations["getChipRace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UnifiedResponse: {
            /**
             * @description 操作是否成功
             * @example true
             */
            success?: boolean;
            /**
             * @description HTTP状态码
             * @example 200
             */
            code?: number;
            /**
             * @description 用户友好消息
             * @example 操作成功
             */
            message?: string;
            /** @description 响应数据 */
            data?: Record<string, never>;
            /**
             * Format: date-time
             * @description ISO 8601时间戳
             * @example 2025-12-29T23:53:41Z
             */
            timestamp?: string;
            /**
             * @description 请求追踪ID
             * @example req_20251229235341
             */
            request_id?: string;
            /** @description 错误详情列表 */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        ErrorDetail: {
            /**
             * @description 错误码
             * @example VALIDATION_ERROR
             */
            code?: string;
            /**
             * @description 错误消息
             * @example 参数验证失败
             */
            message?: string;
            /** @description 详细错误信息 */
            details?: Record<string, never>;
        };
        MarketOverviewData: {
            /**
             * @description 主要市场指数
             * @example {
             *       "sh000001": 3200.5,
             *       "sz399001": 10500.2
             *     }
             */
            market_index?: {
                [key: string]: number;
            };
            /**
             * @description 换手率
             * @example 0.025
             */
            turnover_rate?: number;
            rise_fall_count?: {
                /**
                 * @description 上涨股票数
                 * @example 2500
                 */
                rise?: number;
                /**
                 * @description 下跌股票数
                 * @example 1800
                 */
                fall?: number;
                /**
                 * @description 平盘股票数
                 * @example 300
                 */
                flat?: number;
            };
            /** @description 涨幅榜前N名ETF */
            top_etfs?: components["schemas"]["TopETF"][];
            /**
             * Format: date-time
             * @description 数据时间戳
             */
            timestamp?: string;
        };
        TopETF: {
            /**
             * @description ETF代码
             * @example 510300
             */
            symbol?: string;
            /**
             * @description ETF名称
             * @example 沪深300ETF
             */
            name?: string;
            /**
             * @description 涨跌幅（%）
             * @example 2.5
             */
            change_percent?: number;
        };
        FundFlowData: {
            /**
             * @description 股票代码
             * @example 600519
             */
            symbol?: string;
            /**
             * @description 主力净流入（万元）
             * @example 12500.5
             */
            main_net_inflow?: number;
            /**
             * @description 散户净流入（万元）
             * @example -3200.8
             */
            retail_net_inflow?: number;
            /**
             * @description 大单净流入（万元）
             * @example 8900.3
             */
            big_order_net_inflow?: number;
            /**
             * @description 时间维度（1/3/5/10天）
             * @example 1
             */
            timeframe?: string;
            /**
             * Format: date-time
             * @description 数据时间戳
             */
            timestamp?: string;
        };
        KlineData: {
            /**
             * @description 股票代码
             * @example 600519
             */
            symbol?: string;
            /**
             * @description K线周期
             * @example 1d
             * @enum {string}
             */
            interval?: "1m" | "5m" | "15m" | "30m" | "1h" | "1d";
            /** @description K线数据点 */
            data?: components["schemas"]["KlinePoint"][];
            /**
             * Format: date-time
             * @description 数据时间戳
             */
            timestamp?: string;
        };
        KlinePoint: {
            /**
             * Format: date-time
             * @description 时间戳
             * @example 2025-12-29T00:00:00Z
             */
            timestamp?: string;
            /**
             * @description 开盘价
             * @example 100.5
             */
            open?: number;
            /**
             * @description 最高价
             * @example 102.3
             */
            high?: number;
            /**
             * @description 最低价
             * @example 99.8
             */
            low?: number;
            /**
             * @description 收盘价
             * @example 101.2
             */
            close?: number;
            /**
             * @description 成交量
             * @example 12345678
             */
            volume?: number;
            /**
             * @description 成交额
             * @example 1234567890.12
             */
            amount?: number;
        };
        ETFData: {
            /**
             * @description ETF代码
             * @example 510300
             */
            symbol?: string;
            /**
             * @description ETF名称
             * @example 沪深300ETF
             */
            name?: string;
            /**
             * @description 当前价格
             * @example 4.523
             */
            price?: number;
            /**
             * @description 涨跌幅（%）
             * @example 1.25
             */
            change_percent?: number;
            /**
             * @description 成交量
             * @example 12345678
             */
            volume?: number;
            /**
             * @description 成交额
             * @example 123456789.01
             */
            amount?: number;
            /**
             * @description 市场（SH/SZ）
             * @example SH
             */
            market?: string;
        };
        LongHuBangData: {
            /**
             * Format: date
             * @description 日期
             * @example 2025-12-29
             */
            date?: string;
            /** @description 龙虎榜股票列表 */
            stocks?: components["schemas"]["LongHuBangStock"][];
        };
        LongHuBangStock: {
            /**
             * @description 股票代码
             * @example 600519
             */
            symbol?: string;
            /**
             * @description 股票名称
             * @example 贵州茅台
             */
            name?: string;
            /**
             * @description 上榜原因
             * @example 日涨幅偏离值达7%
             */
            reason?: string;
            /**
             * @description 买入金额（万元）
             * @example 12345.67
             */
            buy_amount?: number;
            /**
             * @description 卖出金额（万元）
             * @example 9876.54
             */
            sell_amount?: number;
        };
        ChipRaceData: {
            /**
             * Format: date
             * @description 日期
             * @example 2025-12-29
             */
            date?: string;
            /** @description 抢筹股票列表 */
            stocks?: components["schemas"]["ChipRaceStock"][];
        };
        ChipRaceStock: {
            /**
             * @description 股票代码
             * @example 600519
             */
            symbol?: string;
            /**
             * @description 股票名称
             * @example 贵州茅台
             */
            name?: string;
            /**
             * @description 抢筹比例（%）
             * @example 85.5
             */
            race_ratio?: number;
            /**
             * @description 主力买入金额（万元）
             * @example 25000.8
             */
            main_buy_amount?: number;
            /**
             * @description 散户买入金额（万元）
             * @example 12500.4
             */
            retail_buy_amount?: number;
        };
        ErrorResponse: components["schemas"]["UnifiedResponse"] & {
            /** @example false */
            success?: unknown;
            /** @example 400 */
            code?: unknown;
            /** @example null */
            data?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMarketOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["MarketOverviewData"];
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFundFlow: {
        parameters: {
            query: {
                /**
                 * @description 股票代码
                 * @example 600519
                 */
                symbol: string;
                /** @description 时间维度（1/3/5/10天） */
                timeframe?: "1" | "3" | "5" | "10";
                /** @description 开始日期（YYYY-MM-DD） */
                start_date?: string;
                /** @description 结束日期（YYYY-MM-DD） */
                end_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["FundFlowData"];
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 股票代码不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getKlineData: {
        parameters: {
            query: {
                /**
                 * @description 股票代码
                 * @example 600519
                 */
                symbol: string;
                /** @description K线周期 */
                interval?: "1m" | "5m" | "15m" | "30m" | "1h" | "1d";
                /** @description 开始日期（YYYY-MM-DD） */
                start_date?: string;
                /** @description 结束日期（YYYY-MM-DD） */
                end_date?: string;
                /** @description 返回数据点数量限制 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["KlineData"];
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 股票代码不存在或无数据 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getETFList: {
        parameters: {
            query?: {
                /** @description ETF代码（精确查询） */
                symbol?: string;
                /** @description 关键词搜索（代码或名称模糊匹配） */
                keyword?: string;
                /** @description 市场类型 */
                market?: "SH" | "SZ";
                /** @description ETF类型 */
                category?: "股票" | "债券" | "商品" | "货币" | "QDII";
                /** @description 返回数量限制 */
                limit?: number;
                /** @description 偏移量（用于分页） */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: {
                            etfs?: components["schemas"]["ETFData"][];
                            /** @description 总数量 */
                            total?: number;
                            /** @description 当前页码 */
                            page?: number;
                            /** @description 每页大小 */
                            page_size?: number;
                        };
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLongHuBang: {
        parameters: {
            query?: {
                /** @description 日期（YYYY-MM-DD），默认为最新交易日 */
                date?: string;
                /** @description 龙虎榜类型（涨幅榜/跌幅榜/全部） */
                type?: "rise" | "fall" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["LongHuBangData"];
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定日期无数据 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getChipRace: {
        parameters: {
            query?: {
                /** @description 日期（YYYY-MM-DD），默认为最新交易日 */
                date?: string;
                /** @description 返回股票数量限制 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功响应 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["ChipRaceData"];
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 指定日期无数据 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
