version: '3.8'

services:
  timescaledb:
    image: docker.1ms.run/timescale/timescaledb-ha:pg17.6-ts2.22.0-oss
    container_name: timescaledb-oss
    restart: unless-stopped
    ports:
      - "5438:5432"  # 已确认的未占用端口，避开冲突
    volumes:
      # 官网指定 PGDATA 路径，宿主机目录按实际权限调整
      - /volume5/docker5/timescale/pgdata:/home/postgres/pgdata/data
      - /volume5/docker5/timescale/conf:/etc/postgresql/17/main/conf.d
    #######################################
    # 核心修复：使用容器内默认 postgres 用户（UID 999），而非宿主机 UID
    # 官网强调：TimescaleDB 镜像内 postgres 用户 UID 固定为 999，GID 固定为 999
    #######################################
    user: "999:999"  # 容器内 postgres 用户的默认 UID/GID，无需修改
    environment:
      # 官网必填初始化配置
      POSTGRES_DB: mystocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: c790414J
      PGDATA: /home/postgres/pgdata/data  # 严格对齐官网 PGDATA 路径
      
      # 官网单节点与扩展配置
      PATRONI_MODE: "standalone"
      PATRONI_SCOPE: "timescale-single-node"
      TIMESCALEDB_TELEMETRY: "off"
      POSTGRES_MULTIPLE_DATABASES: "mystocks"
      TIMESCALEDB_EXTENSION_CREATE_IF_NOT_EXISTS: "true"
      
      # 官网性能与时区配置
      TZ: "Asia/Shanghai"
      PATRONI_POSTGRESQL_PARAMETERS: |
        shared_buffers = 512MB
        work_mem = 32MB
        max_connections = 100
        log_directory = '/home/postgres/pgdata/data/logs'
    # 官网标准健康检查
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s  # 适配 PostgreSQL 17 初始化耗时

networks:
  default:
    driver: bridge