-- TDengine Migration SQL Script
-- Generated by migrate_tdengine_tags.py
-- Execute these commands in TDengine CLI (taos)

-- Adding tags for market_data.tick_data
ALTER STABLE market_data.tick_data ADD TAG txn_id BINARY(64);
ALTER STABLE market_data.tick_data ADD TAG is_valid BOOL;

-- Adding tags for market_data.minute_kline
ALTER STABLE market_data.minute_kline ADD TAG txn_id BINARY(64);
ALTER STABLE market_data.minute_kline ADD TAG is_valid BOOL;

-- Adding tags for market_data.depth_data
ALTER STABLE market_data.depth_data ADD TAG txn_id BINARY(64);
ALTER STABLE market_data.depth_data ADD TAG is_valid BOOL;

-- Adding tags for market_data.minute_kline_1min
ALTER STABLE market_data.minute_kline_1min ADD TAG txn_id BINARY(64);
ALTER STABLE market_data.minute_kline_1min ADD TAG is_valid BOOL;

-- Adding tags for market_data.minute_kline_5min
ALTER STABLE market_data.minute_kline_5min ADD TAG txn_id BINARY(64);
ALTER STABLE market_data.minute_kline_5min ADD TAG is_valid BOOL;

-- Adding tags for market_data.minute_kline_15min
ALTER STABLE market_data.minute_kline_15min ADD TAG txn_id BINARY(64);
ALTER STABLE market_data.minute_kline_15min ADD TAG is_valid BOOL;

-- Adding tags for market_data.minute_kline_30min
ALTER STABLE market_data.minute_kline_30min ADD TAG txn_id BINARY(64);
ALTER STABLE market_data.minute_kline_30min ADD TAG is_valid BOOL;

-- Adding tags for market_data.minute_kline_60min
ALTER STABLE market_data.minute_kline_60min ADD TAG txn_id BINARY(64);
ALTER STABLE market_data.minute_kline_60min ADD TAG is_valid BOOL;

-- Migration Script End
