from __future__ import annotations

from typing import Protocol

from .models import (
    WorkerStatusViewRecord,
    WorkEventRecord,
    WorkItemRecord,
    WorkRequestRecord,
    WorkUpdateRecord,
)


class CollaborationStore(Protocol):
    def upsert_work_item(self, work_item: WorkItemRecord) -> WorkItemRecord: ...

    def get_work_item(self, work_item_id: str) -> WorkItemRecord | None: ...

    def list_work_items(self) -> list[WorkItemRecord]: ...

    def append_work_update(self, update: WorkUpdateRecord) -> WorkUpdateRecord: ...

    def list_work_updates(self, work_item_id: str) -> list[WorkUpdateRecord]: ...

    def create_work_request(self, request: WorkRequestRecord) -> WorkRequestRecord: ...

    def list_work_requests(self, work_item_id: str) -> list[WorkRequestRecord]: ...

    def append_work_event(self, event: WorkEventRecord) -> WorkEventRecord: ...

    def list_work_events(self, work_item_id: str) -> list[WorkEventRecord]: ...

    def upsert_worker_status_view(self, view: WorkerStatusViewRecord) -> WorkerStatusViewRecord: ...

    def get_worker_status_view(self, work_item_id: str) -> WorkerStatusViewRecord | None: ...

    def ensure_indexes(self) -> None: ...
