from __future__ import annotations

from typing import Protocol

from .models import (
    TranscriptEventRecord,
    TranscriptHotBodyRecord,
    TranscriptLegacyIndexRecord,
    TranscriptSessionRecord,
    WorkerStatusViewRecord,
    WorkEventRecord,
    WorkItemRecord,
    WorkRequestRecord,
    WorkUpdateRecord,
)


class CollaborationStore(Protocol):
    def upsert_work_item(self, work_item: WorkItemRecord) -> WorkItemRecord: ...

    def get_work_item(self, work_item_id: str) -> WorkItemRecord | None: ...

    def list_work_items(self) -> list[WorkItemRecord]: ...

    def append_work_update(self, update: WorkUpdateRecord) -> WorkUpdateRecord: ...

    def list_work_updates(self, work_item_id: str) -> list[WorkUpdateRecord]: ...

    def create_work_request(self, request: WorkRequestRecord) -> WorkRequestRecord: ...

    def list_work_requests(self, work_item_id: str) -> list[WorkRequestRecord]: ...

    def append_work_event(self, event: WorkEventRecord) -> WorkEventRecord: ...

    def list_work_events(self, work_item_id: str) -> list[WorkEventRecord]: ...

    def upsert_worker_status_view(self, view: WorkerStatusViewRecord) -> WorkerStatusViewRecord: ...

    def get_worker_status_view(self, work_item_id: str) -> WorkerStatusViewRecord | None: ...

    def upsert_transcript_session(self, session: TranscriptSessionRecord) -> TranscriptSessionRecord: ...

    def get_transcript_session(self, session_id: str) -> TranscriptSessionRecord | None: ...

    def list_transcript_sessions(self, work_item_id: str) -> list[TranscriptSessionRecord]: ...

    def append_transcript_event(self, event: TranscriptEventRecord) -> TranscriptEventRecord: ...

    def list_transcript_events(self, session_id: str) -> list[TranscriptEventRecord]: ...

    def upsert_transcript_hot_body(self, hot_body: TranscriptHotBodyRecord) -> TranscriptHotBodyRecord: ...

    def get_transcript_hot_body(self, session_id: str) -> TranscriptHotBodyRecord | None: ...

    def append_transcript_legacy_index(
        self, legacy_index: TranscriptLegacyIndexRecord
    ) -> TranscriptLegacyIndexRecord: ...

    def list_transcript_legacy_indexes(self, work_item_id: str) -> list[TranscriptLegacyIndexRecord]: ...

    def ensure_indexes(self) -> None: ...
