
import type { components } from './types-1.components';

// Operations type stub (auto-generated by openapi-typescript)
export interface operations {
    "getMarketOverview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["MarketOverviewData"];
                    };
                };
            };
        };
    };
    "getFundFlow": {
        parameters: {
            query?: {
                symbol?: string;
                timeframe?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["FundFlowData"];
                    };
                };
            };
        };
    };
    "getKlineData": {
        parameters: {
            query?: {
                symbol?: string;
                interval?: "1m" | "5m" | "15m" | "30m" | "1h" | "1d";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["KlineData"];
                    };
                };
            };
        };
    };
    "getETFList": {
        parameters: {
            query?: {
                search?: string;
                market?: string;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["ETFData"][];
                    };
                };
            };
        };
    };
    "getLongHuBang": {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["LongHuBangData"];
                    };
                };
            };
        };
    };
    "getChipRace": {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["UnifiedResponse"] & {
                        data?: components["schemas"]["ChipRaceData"];
                    };
                };
            };
        };
    };
}

export interface paths {
    "/api/market/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取市场概览
         * @description 获取A股市场整体概览数据，包括：
         *     - 主要市场指数（上证指数、深证成指等）
         *     - 市场涨跌统计
         *     - 换手率
         *     - 涨幅榜前N名ETF
         */
        get: operations["getMarketOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/fund-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询资金流向
         * @description 查询指定股票的资金流向数据，包括：
         *     - 主力资金流向
         *     - 散户资金流向
         *     - 大单资金流向
         */
        get: operations["getFundFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/kline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取K线数据
         * @description 获取指定股票的K线数据，支持：
         *     - 分钟K：1m, 5m, 15m, 30m
         *     - 小时K：1h
         *     - 日K：1d
         */
        get: operations["getKlineData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/etf/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询ETF列表
         * @description 查询ETF列表，支持多种筛选条件：
         *     - 按代码或名称搜索
         *     - 按市场筛选（上海/深圳）
         *     - 按类型筛选（股票/债券/商品/货币/QDII）
         */
        get: operations["getETFList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/lhb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询龙虎榜数据
         * @description 查询指定日期的龙虎榜数据，包括：
         *     - 涨幅榜上榜股票
         *     - 跌幅榜上榜股票
         *     - 异常波动股票
         */
        get: operations["getLongHuBang"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/chip-race": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询竞价抢筹数据
         * @description 查询指定日期的竞价抢筹数据，包括：
         *     - 开盘抢筹比例
         *     - 主力vs散户买入对比
         *     - 热门抢筹股票排行
         */
        get: operations["getChipRace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}

export type webhooks = Record<string, never>;

export type { $defs, components } from './types-1.components';
