# scripts/dev/smart_coordinator.py

"""智能协调器 - 让main更轻松

使用规则引擎自动处理常见协调场景：
1. 阻塞自动解决
2. 空闲资源自动分配
3. 冲突自动预防
"""

import os
import sys
import time
from datetime import datetime
from pathlib import Path


sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# 导入基础协调器
try:
    from cli_coordinator import CLICoordinator
except ImportError:
    # 如果导入失败，定义基础类
    class CLICoordinator:
        def __init__(self, clis_dir="CLIS"):
            self.clis_dir = Path(clis_dir)

        def scan_all_status(self):
            statuses = {}
            for cli_dir in self.clis_dir.iterdir():
                if cli_dir.is_dir() and cli_dir.name != "main":
                    status_file = cli_dir / "STATUS.md"
                    if status_file.exists():
                        statuses[cli_dir.name] = self._parse_status(status_file)
            return statuses

        def _parse_status(self, status_file):
            content = status_file.read_text()
            # 简化的状态解析
            return {
                "name": status_file.parent.name,
                "state": "unknown",
                "current_task": None,
                "last_update": None,
                "blocked_on": None,
                "waiting_time": 0,
            }


class SmartCoordinator(CLICoordinator):
    """智能协调器 - 规则引擎"""

    def __init__(self, clis_dir="CLIS"):
        super().__init__(clis_dir)
        self.coordination_log = self.clis_dir / "SHARED" / "COORDINATION_LOG.md"
        self.coordination_log.parent.mkdir(parents=True, exist_ok=True)

        # 初始化规则
        self.rules = [
            BlockageResolutionRule(self),
            IdleResourceRule(self),
            ConflictPreventionRule(self),
            HealthCheckRule(self),
        ]

    def auto_coordinate(self):
        """自动执行协调规则"""
        print("\n🤖 智能协调器启动...")

        # 扫描所有CLI状态
        statuses = self.scan_all_status()

        print(f"扫描到 {len(statuses)} 个CLI")

        # 执行所有规则
        all_actions = []
        for rule in self.rules:
            actions = rule.evaluate(statuses)
            all_actions.extend(actions)

        # 执行动作
        if all_actions:
            print(f"\n生成 {len(all_actions)} 个协调动作...")

            for i, action in enumerate(all_actions, 1):
                print(f"\n[{i}/{len(all_actions)}] 执行: {action.type}")
                self.execute_action(action)

            # 记录协调日志
            self.log_coordination(all_actions)

            return len(all_actions)
        print("✅ 无需协调，系统运行正常")
        return 0

    def execute_action(self, action):
        """执行协调动作"""
        if action.type == "reassign":
            self.send_reassign_message(action)
        elif action.type == "alert":
            self.send_alert_message(action)
        elif action.type == "notify":
            self.send_notify_message(action)

    def send_reassign_message(self, action):
        """发送重新分配消息"""
        message = f"""---
**From**: CLI-main
**To**: {action.to_cli}
**Type**: REQUEST
**Priority**: HIGH
**Timestamp**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**AutoGenerated**: true

**Subject**: 协作请求：协助{action.from_cli}

**Description**:
{action.reason}

**Blocked Task**: {action.blocked_task}

**Action Required**:
请评估是否可以协助完成依赖任务，或者执行以下独立任务：
{action.suggested_task}

**Expected Response**: 15分钟内

此消息由智能协调器自动生成，如无法协助，请回复main。
"""

        # 发送消息
        self._send_message(action.to_cli, message)
        print(f"📧 已发送协调消息到 {action.to_cli}")

    def send_alert_message(self, action):
        """发送告警消息"""
        message = f"""---
**From**: CLI-main
**To**: {action.to_cli}
**Type**: ALERT
**Priority**: HIGH
**Timestamp**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**AutoGenerated**: true

**Subject**: 文件锁持有时间过长提醒

**Description**:
{action.reason}

**Action Required**:
请尽快完成当前工作并释放文件锁。

此消息由智能协调器自动生成。
"""

        self._send_message(action.to_cli, message)
        print(f"🚨 已发送告警到 {action.to_cli}")

    def send_notify_message(self, action):
        """发送通知消息"""
        message = f"""---
**From**: CLI-main
**To**: {action.to_cli}
**Type**: NOTIFICATION
**Priority**: MEDIUM
**Timestamp**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**AutoGenerated**: true

**Subject**: {action.reason}

此消息由智能协调器自动生成。
"""

        self._send_message(action.to_cli, message)
        print(f"📢 已发送通知到 {action.to_cli}")

    def _send_message(self, to_cli, message):
        """发送消息到指定CLI"""
        mailbox_dir = self.clis_dir / to_cli / "mailbox"
        mailbox_dir.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        message_file = mailbox_dir / f"main_auto_{timestamp}.md"

        with open(message_file, "w", encoding="utf-8") as f:
            f.write(message)

    def log_coordination(self, actions):
        """记录协调日志"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        with open(self.coordination_log, "a", encoding="utf-8") as f:
            f.write(f"\n## 自动协调: {timestamp}\n\n")

            for action in actions:
                f.write(f"- **类型**: {action.type}\n")
                f.write(f"- **涉及CLI**: {action.from_cli} → {action.to_cli}\n")
                f.write(f"- **原因**: {action.reason}\n")
                f.write(f"- **状态**: {'✅ 已执行' if action.executed else '⏸️ 待执行'}\n")
                f.write("\n")


class CoordinationAction:
    """协调动作"""

    def __init__(self, type, from_cli, to_cli, reason, **kwargs):
        self.type = type
        self.from_cli = from_cli
        self.to_cli = to_cli
        self.reason = reason
        self.executed = False

        for key, value in kwargs.items():
            setattr(self, key, value)


class BlockageResolutionRule:
    """阻塞自动解决规则"""

    def __init__(self, coordinator):
        self.coordinator = coordinator

    def evaluate(self, statuses):
        """评估阻塞情况并生成动作"""
        actions = []

        for cli, status in statuses.items():
            if status["state"] == "blocked":
                # 计算等待时间
                if status["last_update"]:
                    try:
                        last_update = datetime.strptime(status["last_update"], "%Y-%m-%d %H:%M:%S")
                        waiting_time = (datetime.now() - last_update).total_seconds() / 60
                    except:
                        waiting_time = 0
                else:
                    waiting_time = 0

                # 规则1: 等待时间 > 60分钟，自动分配协助
                if waiting_time > 60:
                    idle_cli = self._find_idle_cli(statuses)
                    if idle_cli:
                        actions.append(
                            CoordinationAction(
                                type="reassign",
                                from_cli=cli,
                                to_cli=idle_cli,
                                reason=f"自动协调: {cli}被阻塞{waiting_time:.0f}分钟",
                                blocked_task=status["current_task"],
                                suggested_task="执行独立任务池中的任务或协助依赖任务",
                            )
                        )

        return actions

    def _find_idle_cli(self, statuses):
        """查找空闲CLI"""
        for cli, status in statuses.items():
            if status["state"] == "idle":
                return cli
        return None


class IdleResourceRule:
    """空闲资源自动分配规则"""

    def __init__(self, coordinator):
        self.coordinator = coordinator

    def evaluate(self, statuses):
        """评估空闲资源并生成动作"""
        actions = []

        idle_clis = [cli for cli, status in statuses.items() if status["state"] == "idle"]

        if not idle_clis:
            return actions

        # 读取独立任务池
        tasks_pool = self.coordinator.clis_dir / "SHARED" / "TASKS_POOL.md"
        if tasks_pool.exists():
            with open(tasks_pool) as f:
                content = f.read()

            # 解析独立任务
            available_tasks = self._parse_tasks_pool(content)

            # 为空闲CLI分配任务
            for i, idle_cli in enumerate(idle_clis):
                if i < len(available_tasks):
                    task = available_tasks[i]

                    actions.append(
                        CoordinationAction(
                            type="notify",
                            from_cli="main",
                            to_cli=idle_cli,
                            reason=f"您当前空闲，建议执行独立任务: {task['name']}",
                            suggested_task=task,
                        )
                    )

        return actions

    def _parse_tasks_pool(self, content):
        """解析任务池"""
        # 简化实现，实际应该解析markdown
        return []


class ConflictPreventionRule:
    """冲突自动预防规则"""

    def __init__(self, coordinator):
        self.coordinator = coordinator

    def evaluate(self, statuses):
        """评估潜在冲突并生成动作"""
        actions = []

        # 检查文件锁
        locks_dir = self.coordinator.clis_dir / "locks"

        if locks_dir.exists():
            for lock_file in locks_dir.glob("*.lock"):
                try:
                    with open(lock_file) as f:
                        content = f.read()
                        holder = content.split("\n")[0]
                        waiting_time = time.time() - float(content.split("\n")[1])

                    # 规则: 锁定时间 > 30分钟，发送提醒
                    if waiting_time > 1800:  # 30分钟
                        actions.append(
                            CoordinationAction(
                                type="alert",
                                from_cli="main",
                                to_cli=holder,
                                reason=f"文件锁持有时间过长({waiting_time / 60:.0f}分钟)，请尽快完成并释放锁",
                                lock_file=lock_file.name,
                            )
                        )

                except:
                    pass

        return actions


class HealthCheckRule:
    """健康检查规则"""

    def __init__(self, coordinator):
        self.coordinator = coordinator

    def evaluate(self, statuses):
        """评估CLI健康状态并生成动作"""
        actions = []

        for cli, status in statuses.items():
            # 检查最后更新时间
            if status["last_update"]:
                try:
                    last_update = datetime.strptime(status["last_update"], "%Y-%m-%d %H:%M:%S")
                    idle_time = (datetime.now() - last_update).total_seconds() / 60

                    # 规则: 超过10分钟未更新，发送提醒
                    if idle_time > 10:
                        actions.append(
                            CoordinationAction(
                                type="notify",
                                from_cli="main",
                                to_cli=cli,
                                reason=f"STATUS.md已{idle_time:.0f}分钟未更新，请及时更新",
                            )
                        )

                except:
                    pass

        return actions


def main():
    """主函数"""
    import argparse

    parser = argparse.ArgumentParser(description="智能CLI协调器")
    parser.add_argument("--auto", action="store_true", help="自动执行协调")
    parser.add_argument("--clis-dir", default="CLIS", help="CLI目录")

    args = parser.parse_args()

    coordinator = SmartCoordinator(args.clis_dir)

    if args.auto:
        action_count = coordinator.auto_coordinate()
        print(f"\n✅ 协调完成，执行了 {action_count} 个动作")


if __name__ == "__main__":
    main()
