/**
 * Page Configuration - Auto-generated by generate-page-config.js
 * 
 * This file is AUTO-GENERATED. Manual changes will be overwritten.
 * To make permanent changes, update the generation script and run:
 *   npm run generate-page-config
 * 
 * Generated at: 2026-03-22T02:31:38.549Z
 * Routes processed: 35
 */

import type { PageConfigType, TabConfig, MonolithicPageConfig, StandardPageConfig, PageConfig } from '@/types/pageConfig'

// Tab configurations for monolithic components
const TAB_CONFIGS: Record<string, TabConfig[]> = {
}

// Standard page configurations (non-monolithic)
const PAGE_CONFIGS: Record<string, StandardPageConfig> = {
  'dashboard': {
    type: 'page',
    routePath: 'dashboard',
    title: '交易室',
    description: '交易室概览',
    component: 'ArtDecoDashboard.vue',
    requiresAuth: true,
  },
  'market-realtime': {
    type: 'page',
    routePath: 'realtime',
    title: '实时行情',
    description: '实时行情',
    apiEndpoint: '/api/market/realtime',
    wsChannel: 'market:realtime',
    component: 'Realtime.vue',
    requiresAuth: true,
  },
  'market-technical': {
    type: 'page',
    routePath: 'technical',
    title: 'K线分析',
    description: '技术指标',
    apiEndpoint: '/api/technical/indicators',
    wsChannel: 'market:technical',
    component: 'Technical.vue',
    requiresAuth: true,
  },
  'market-lhb': {
    type: 'page',
    routePath: 'lhb',
    title: '龙虎榜',
    description: '龙虎榜',
    apiEndpoint: '/api/v1/market/lhb',
    component: 'LHB.vue',
    requiresAuth: true,
  },
  'data-industry': {
    type: 'page',
    routePath: 'industry',
    title: '板块动向',
    description: '板块动向',
    apiEndpoint: '/api/data/industry',
    wsChannel: 'data:industry',
    component: 'Industry.vue',
    requiresAuth: true,
  },
  'data-concept': {
    type: 'page',
    routePath: 'concept',
    title: '概念动向',
    description: '概念动向',
    apiEndpoint: '/api/v2/market/sector/fund-flow?sector_type=概念',
    component: 'Concepts.vue',
    requiresAuth: true,
  },
  'data-fund-flow': {
    type: 'page',
    routePath: 'fund-flow',
    title: '资金流向',
    description: '资金流向',
    apiEndpoint: '/api/akshare/market/fund-flow',
    component: 'FundFlow.vue',
    requiresAuth: true,
  },
  'data-indicator': {
    type: 'page',
    routePath: 'indicator',
    title: '指标分析',
    description: '指标分析',
    apiEndpoint: '/api/data/indicator',
    wsChannel: 'data:indicator',
    component: 'Advanced.vue',
    requiresAuth: true,
  },
  'watchlist-manage': {
    type: 'page',
    routePath: 'manage',
    title: '组合管理',
    description: '组合管理',
    apiEndpoint: '/api/v1/monitoring/watchlists',
    component: 'Manage.vue',
    requiresAuth: true,
  },
  'watchlist-signals': {
    type: 'page',
    routePath: 'signals',
    title: '信号雷达',
    description: '信号雷达',
    apiEndpoint: '/api/watchlist/signals',
    wsChannel: 'watchlist:signals',
    component: 'Signals.vue',
    requiresAuth: true,
  },
  'watchlist-screener': {
    type: 'page',
    routePath: 'screener',
    title: '策略选股',
    description: '策略选股',
    apiEndpoint: '/api/watchlist/screener',
    wsChannel: 'watchlist:screener',
    component: 'Screener.vue',
    requiresAuth: true,
  },
  'strategy-repo': {
    type: 'page',
    routePath: 'repo',
    title: '策略仓库',
    description: '策略仓库',
    apiEndpoint: '/api/v1/strategy/strategies',
    component: 'List.vue',
    requiresAuth: true,
  },
  'strategy-parameters': {
    type: 'page',
    routePath: 'parameters',
    title: '策略参数',
    description: '策略参数',
    apiEndpoint: '/api/strategy/parameters',
    wsChannel: 'strategy:parameters',
    component: 'Parameters.vue',
    requiresAuth: true,
  },
  'strategy-signals': {
    type: 'page',
    routePath: 'signals',
    title: '策略信号',
    description: '策略信号',
    apiEndpoint: '/api/strategy/signals',
    wsChannel: 'strategy:signals',
    component: 'StrategySignalsTab.vue',
    requiresAuth: true,
  },
  'strategy-backtest': {
    type: 'page',
    routePath: 'backtest',
    title: '回测引擎',
    description: '策略回测',
    apiEndpoint: '/api/v1/strategy/backtest',
    component: 'Backtest.vue',
    requiresAuth: true,
  },
  'strategy-gpu': {
    type: 'page',
    routePath: 'gpu',
    title: '加速监控',
    description: '加速监控',
    apiEndpoint: '/api/strategy/gpu',
    wsChannel: 'strategy:gpu',
    component: 'BacktestGPU.vue',
    requiresAuth: true,
  },
  'strategy-opt': {
    type: 'page',
    routePath: 'opt',
    title: '参数优化',
    description: '参数优化',
    apiEndpoint: '/api/strategy/opt',
    wsChannel: 'strategy:opt',
    component: 'Optimization.vue',
    requiresAuth: true,
  },
  'strategy-pos': {
    type: 'page',
    routePath: 'pos',
    title: '仓位管理',
    description: '仓位管理',
    apiEndpoint: '/api/v1/trade/positions',
    component: 'ArtDecoTradingPositions.vue',
    requiresAuth: true,
  },
  'trade-positions': {
    type: 'page',
    routePath: 'positions',
    title: '头寸管理',
    description: '头寸管理',
    apiEndpoint: '/api/trade/positions',
    wsChannel: 'trade:positions',
    component: 'Center.vue',
    requiresAuth: true,
  },
  'trade-terminal': {
    type: 'page',
    routePath: 'terminal',
    title: '交易操作',
    description: '交易操作',
    apiEndpoint: '/api/trade/terminal',
    wsChannel: 'trade:terminal',
    component: 'TradingDashboard.vue',
    requiresAuth: true,
  },
  'trade-signals': {
    type: 'page',
    routePath: 'signals',
    title: '信号监控',
    description: '信号监控',
    apiEndpoint: '/api/trade/signals',
    wsChannel: 'trade:signals',
    component: 'Signals.vue',
    requiresAuth: true,
  },
  'trade-portfolio': {
    type: 'page',
    routePath: 'portfolio',
    title: '持仓透视',
    description: '持仓透视',
    apiEndpoint: '/api/trade/portfolio',
    wsChannel: 'trade:portfolio',
    component: 'Portfolio.vue',
    requiresAuth: true,
  },
  'trade-history': {
    type: 'page',
    routePath: 'history',
    title: '历史对账',
    description: '历史对账',
    apiEndpoint: '/api/trade/history',
    wsChannel: 'trade:history',
    component: 'History.vue',
    requiresAuth: true,
  },
  'risk-overview': {
    type: 'page',
    routePath: 'overview',
    title: '风险概览',
    description: '风险概览',
    apiEndpoint: '/api/risk/overview',
    wsChannel: 'risk:overview',
    component: 'RiskOverviewTab.vue',
    requiresAuth: true,
  },
  'risk-pnl': {
    type: 'page',
    routePath: 'pnl',
    title: '组合盈亏',
    description: '组合盈亏',
    apiEndpoint: '/api/risk/pnl',
    wsChannel: 'risk:pnl',
    component: 'PortfolioOverviewTab.vue',
    requiresAuth: true,
  },
  'risk-stop-loss': {
    type: 'page',
    routePath: 'stop-loss',
    title: '止损雷达',
    description: '止损雷达',
    apiEndpoint: '/api/risk/stop/loss',
    wsChannel: 'risk:stop/loss',
    component: 'StopLossMonitorTab.vue',
    requiresAuth: true,
  },
  'risk-alerts': {
    type: 'page',
    routePath: 'alerts',
    title: '告警中心',
    description: '告警中心',
    apiEndpoint: '/api/risk/alerts',
    wsChannel: 'risk:alerts',
    component: 'ArtDecoRiskAlerts.vue',
    requiresAuth: true,
  },
  'risk-news': {
    type: 'page',
    routePath: 'news',
    title: '舆情预警',
    description: '舆情预警',
    apiEndpoint: '/api/risk/news',
    wsChannel: 'risk:news',
    component: 'ArtDecoAnnouncementMonitor.vue',
    requiresAuth: true,
  },
  'system-config': {
    type: 'page',
    routePath: 'config',
    title: '系统配置',
    description: '系统配置',
    apiEndpoint: '/api/system/config',
    wsChannel: 'system:config',
    component: 'ArtDecoSystemSettings.vue',
    requiresAuth: true,
  },
  'system-health': {
    type: 'page',
    routePath: 'health',
    title: '健康矩阵',
    description: '健康矩阵',
    apiEndpoint: '/api/system/health',
    wsChannel: 'system:health',
    component: 'SystemHealthTab.vue',
    requiresAuth: true,
  },
  'system-api': {
    type: 'page',
    routePath: 'api',
    title: 'API 终端',
    description: 'API 终端',
    apiEndpoint: '/api/system/api',
    wsChannel: 'system:api',
    component: 'ArtDecoMonitoringDashboard.vue',
    requiresAuth: true,
  },
  'system-data': {
    type: 'page',
    routePath: 'data',
    title: '数据源管理',
    description: '数据源管理',
    apiEndpoint: '/api/system/data',
    wsChannel: 'system:data',
    component: 'ArtDecoDataManagement.vue',
    requiresAuth: true,
  },
  'stock-graphics': {
    type: 'page',
    routePath: 'graphics/:symbol',
    title: '股票图形',
    description: '股票图形',
    apiEndpoint: '/api/stock/graphics',
    wsChannel: 'stock:graphics',
    component: 'KLineAnalysis.vue',
    requiresAuth: true,
  },
  'stock-news': {
    type: 'page',
    routePath: 'news/:symbol',
    title: '相关新闻',
    description: '相关新闻',
    apiEndpoint: '/api/stock/news',
    wsChannel: 'stock:news',
    component: 'AnnouncementMonitor.vue',
    requiresAuth: true,
  },
  'not-found': {
    type: 'page',
    routePath: '/:pathMatch(.*)*',
    title: 'Page Not Found',
    description: 'Page Not Found',
    apiEndpoint: '/api/not/found',
    wsChannel: 'not:found',
    component: 'NotFound.vue',
    requiresAuth: false,
  },
}

// Monolithic page configurations (components with multiple tabs)
const MONOLITHIC_CONFIGS: Record<string, MonolithicPageConfig> = {
}

// Combined PAGE_CONFIG for backward compatibility
export const PAGE_CONFIG: Record<string, PageConfig> = {
  ...PAGE_CONFIGS,
  ...MONOLITHIC_CONFIGS,
}

// Type guards
export function isRouteName(name: string): name is keyof typeof PAGE_CONFIG {
  return name in PAGE_CONFIG
}

export function isMonolithicConfig(config: PageConfig): config is MonolithicPageConfig {
  return config.type === 'monolithic'
}

export function isStandardConfig(config: PageConfig): config is StandardPageConfig {
  return config.type === 'page'
}

// Helper functions
export function getPageConfig(routeName: string): PageConfig | undefined {
  return PAGE_CONFIG[routeName]
}

export function getTabConfig(routeName: string, tabId: string): TabConfig | undefined {
  const config = PAGE_CONFIG[routeName]
  if (config && isMonolithicConfig(config)) {
    return config.tabs.find(tab => tab.id === tabId)
  }
  return undefined
}

export function getTabsForComponent(component: string): TabConfig[] {
  return TAB_CONFIGS[component] || []
}

// Export types for external use
export type { PageConfigType, TabConfig, MonolithicPageConfig, StandardPageConfig, PageConfig }
