/**
 * Page Configuration - Auto-generated by generate-page-config.js
 * 
 * This file is AUTO-GENERATED. Manual changes will be overwritten.
 * To make permanent changes, update the generation script and run:
 *   npm run generate-page-config
 * 
 * Generated at: 2026-02-03T05:09:50.736Z
 * Routes processed: 36
 */

import type { PageConfigType, TabConfig, MonolithicPageConfig, StandardPageConfig, PageConfig } from '@/types/pageConfig'

// Tab configurations for monolithic components
const TAB_CONFIGS: Record<string, TabConfig[]> = {
  'ArtDecoMarketData.vue': [
    {
      id: 'fund-flow',
      apiEndpoint: '/api/market/fund-flow',
      wsChannel: 'market:fund-flow',
    },
    {
      id: 'etf',
      apiEndpoint: '/api/market/etf',
      wsChannel: 'market:etf',
    },
    {
      id: 'concepts',
      apiEndpoint: '/api/market/concept',
      wsChannel: 'market:concept',
    },
    {
      id: 'lhb',
      apiEndpoint: '/api/market/longhubang',
      wsChannel: 'market:longhubang',
    },
    {
      id: 'auction',
      apiEndpoint: '/api/market/auction',
      wsChannel: 'market:auction',
    },
    {
      id: 'institution',
      apiEndpoint: '/api/market/institution',
      wsChannel: 'market:institution',
    },
  ],
  'ArtDecoStockManagement.vue': [
    {
      id: 'overview',
      apiEndpoint: '/api/stock/overview',
      wsChannel: 'stock:overview',
    },
    {
      id: 'watchlist',
      apiEndpoint: '/api/stock/watchlist',
      wsChannel: 'stock:watchlist',
    },
    {
      id: 'positions',
      apiEndpoint: '/api/stock/positions',
      wsChannel: 'stock:positions',
    },
    {
      id: 'attribution',
      apiEndpoint: '/api/trading/attribution',
      wsChannel: 'trading:attribution',
    },
    {
      id: 'history',
      apiEndpoint: '/api/trading/history',
      wsChannel: 'trading:history',
    },
    {
      id: 'strategy',
      apiEndpoint: '/api/strategy/management',
      wsChannel: 'strategy:management',
    },
  ],
}

// Standard page configurations (non-monolithic)
const PAGE_CONFIGS: Record<string, StandardPageConfig> = {
  'dashboard': {
    type: 'page',
    routePath: 'dashboard',
    title: '仪表盘',
    description: '仪表盘概览',
    apiEndpoint: '/api/dashboard/overview',
    wsChannel: 'dashboard:realtime',
    component: 'ArtDecoDashboard.vue',
    requiresAuth: true,
  },
  'market-realtime': {
    type: 'page',
    routePath: 'realtime',
    title: '实时行情',
    description: '实时行情',
    apiEndpoint: '/api/market/realtime',
    wsChannel: 'market:realtime',
    component: 'ArtDecoMarketQuotes.vue',
    requiresAuth: true,
  },
  'market-overview': {
    type: 'page',
    routePath: 'overview',
    title: '市场概览',
    description: '市场概览',
    apiEndpoint: '/api/market/overview',
    wsChannel: 'market:overview',
    component: 'ArtDecoMarketOverview.vue',
    requiresAuth: true,
  },
  'market-analysis': {
    type: 'page',
    routePath: 'analysis',
    title: '市场分析',
    description: '市场分析',
    apiEndpoint: '/api/market/analysis',
    wsChannel: 'market:analysis',
    component: 'ArtDecoMarketAnalysis.vue',
    requiresAuth: true,
  },
  'market-industry': {
    type: 'page',
    routePath: 'industry',
    title: '行业分析',
    description: '行业分析',
    apiEndpoint: '/api/market/industry',
    wsChannel: 'market:industry',
    component: 'ArtDecoIndustryAnalysis.vue',
    requiresAuth: true,
  },
  'market-technical': {
    type: 'page',
    routePath: 'technical',
    title: '技术指标',
    description: '技术指标',
    apiEndpoint: '/api/technical/indicators',
    wsChannel: 'market:technical',
    component: 'ArtDecoMarketQuotes.vue',
    requiresAuth: true,
  },
  'trading-signals': {
    type: 'page',
    routePath: 'signals',
    title: '交易信号',
    description: '交易信号',
    apiEndpoint: '/api/trading/signals',
    wsChannel: 'trading:signals',
    component: 'ArtDecoTradingSignals.vue',
    requiresAuth: true,
  },
  'trading-history': {
    type: 'page',
    routePath: 'history',
    title: '历史订单',
    description: '历史订单',
    apiEndpoint: '/api/trading/history',
    wsChannel: 'trading:history',
    component: 'ArtDecoTradingHistory.vue',
    requiresAuth: true,
  },
  'trading-positions': {
    type: 'page',
    routePath: 'positions',
    title: '持仓监控',
    description: '持仓监控',
    apiEndpoint: '/api/trading/positions',
    wsChannel: 'trading:positions',
    component: 'ArtDecoTradingPositions.vue',
    requiresAuth: true,
  },
  'trading-performance': {
    type: 'page',
    routePath: 'performance',
    title: '绩效分析',
    description: '绩效分析',
    apiEndpoint: '/api/trading/performance',
    wsChannel: 'trading:performance',
    component: 'ArtDecoPerformanceAnalysis.vue',
    requiresAuth: true,
  },
  'trading-attribution': {
    type: 'page',
    routePath: 'attribution',
    title: '绩效归因',
    description: '绩效归因',
    apiEndpoint: '/api/trading/attribution',
    wsChannel: 'trading:attribution',
    component: 'ArtDecoAttributionAnalysis.vue',
    requiresAuth: true,
  },
  'strategy-design': {
    type: 'page',
    routePath: 'design',
    title: '策略设计',
    description: '策略设计',
    apiEndpoint: '/api/strategy/design',
    wsChannel: 'strategy:design',
    component: 'ArtDecoStrategyManagement.vue',
    requiresAuth: true,
  },
  'strategy-management': {
    type: 'page',
    routePath: 'management',
    title: '策略管理',
    description: '策略管理',
    apiEndpoint: '/api/strategy/management',
    wsChannel: 'strategy:management',
    component: 'ArtDecoStrategyManagement.vue',
    requiresAuth: true,
  },
  'strategy-backtest': {
    type: 'page',
    routePath: 'backtest',
    title: '策略回测',
    description: '策略回测',
    apiEndpoint: '/api/strategy/backtest',
    wsChannel: 'strategy:backtest',
    component: 'ArtDecoBacktestAnalysis.vue',
    requiresAuth: true,
  },
  'strategy-gpu-backtest': {
    type: 'page',
    routePath: 'gpu-backtest',
    title: 'GPU加速回测',
    description: 'GPU加速回测',
    apiEndpoint: '/api/strategy/gpu-backtest',
    wsChannel: 'strategy:gpu-backtest',
    component: 'ArtDecoBacktestAnalysis.vue',
    requiresAuth: true,
  },
  'strategy-optimization': {
    type: 'page',
    routePath: 'optimization',
    title: '参数优化',
    description: '参数优化',
    apiEndpoint: '/api/strategy/optimization',
    wsChannel: 'strategy:optimization',
    component: 'ArtDecoStrategyOptimization.vue',
    requiresAuth: true,
  },
  'risk-overview': {
    type: 'page',
    routePath: 'overview',
    title: '风险概览',
    description: '风险概览',
    apiEndpoint: '/api/risk/overview',
    wsChannel: 'risk:overview',
    component: 'ArtDecoMarketQuotes.vue',
    requiresAuth: true,
  },
  'risk-alerts': {
    type: 'page',
    routePath: 'alerts',
    title: '告警中心',
    description: '告警中心',
    apiEndpoint: '/api/risk/alerts',
    wsChannel: 'risk:alerts',
    component: 'ArtDecoMarketQuotes.vue',
    requiresAuth: true,
  },
  'risk-indicators': {
    type: 'page',
    routePath: 'indicators',
    title: '风险指标',
    description: '风险指标',
    apiEndpoint: '/api/risk/indicators',
    wsChannel: 'risk:indicators',
    component: 'ArtDecoMarketQuotes.vue',
    requiresAuth: true,
  },
  'risk-sentiment': {
    type: 'page',
    routePath: 'sentiment',
    title: '舆情监控',
    description: '舆情监控',
    apiEndpoint: '/api/risk/sentiment',
    wsChannel: 'risk:sentiment',
    component: 'ArtDecoMarketQuotes.vue',
    requiresAuth: true,
  },
  'risk-announcement': {
    type: 'page',
    routePath: 'announcement',
    title: '公告监控',
    description: '公告监控',
    apiEndpoint: '/api/risk/announcement',
    wsChannel: 'risk:announcement',
    component: 'ArtDecoMarketQuotes.vue',
    requiresAuth: true,
  },
  'system-monitoring': {
    type: 'page',
    routePath: 'monitoring',
    title: '运维监控',
    description: '运维监控',
    apiEndpoint: '/api/system/monitoring',
    wsChannel: 'system:monitoring',
    component: 'ArtDecoMonitoringDashboard.vue',
    requiresAuth: true,
  },
  'system-settings': {
    type: 'page',
    routePath: 'settings',
    title: '系统设置',
    description: '系统设置',
    apiEndpoint: '/api/system/settings',
    wsChannel: 'system:settings',
    component: 'ArtDecoSystemSettings.vue',
    requiresAuth: true,
  },
  'system-data-update': {
    type: 'page',
    routePath: 'data-update',
    title: '数据更新',
    description: '数据更新',
    apiEndpoint: '/api/system/data-update',
    wsChannel: 'system:data-update',
    component: 'ArtDecoDataManagement.vue',
    requiresAuth: true,
  },
  'system-data-quality': {
    type: 'page',
    routePath: 'data-quality',
    title: '数据质量',
    description: '数据质量',
    apiEndpoint: '/api/system/data-quality',
    wsChannel: 'system:data-quality',
    component: 'ArtDecoDataManagement.vue',
    requiresAuth: true,
  },
  'system-api-health': {
    type: 'page',
    routePath: 'api-health',
    title: 'API 健康',
    description: 'API健康',
    apiEndpoint: '/api/system/api-health',
    wsChannel: 'system:api-health',
    component: 'ArtDecoMonitoringDashboard.vue',
    requiresAuth: true,
  },
}

// Monolithic page configurations (components with multiple tabs)
const MONOLITHIC_CONFIGS: Record<string, MonolithicPageConfig> = {
  'market-fund-flow': {
    type: 'monolithic',
    routePath: 'fund-flow',
    title: '资金流向',
    description: '资金流向',
    component: 'ArtDecoMarketData.vue',
    tabs: TAB_CONFIGS['ArtDecoMarketData.vue'] || [],
    requiresAuth: true,
  },
  'market-etf': {
    type: 'monolithic',
    routePath: 'etf',
    title: 'ETF行情',
    description: 'ETF行情',
    component: 'ArtDecoMarketData.vue',
    tabs: TAB_CONFIGS['ArtDecoMarketData.vue'] || [],
    requiresAuth: true,
  },
  'market-concept': {
    type: 'monolithic',
    routePath: 'concept',
    title: '概念板块',
    description: '概念板块',
    component: 'ArtDecoMarketData.vue',
    tabs: TAB_CONFIGS['ArtDecoMarketData.vue'] || [],
    requiresAuth: true,
  },
  'market-auction': {
    type: 'monolithic',
    routePath: 'auction',
    title: '竞价抢筹',
    description: '竞价抢筹',
    component: 'ArtDecoMarketData.vue',
    tabs: TAB_CONFIGS['ArtDecoMarketData.vue'] || [],
    requiresAuth: true,
  },
  'market-longhubang': {
    type: 'monolithic',
    routePath: 'longhubang',
    title: '龙虎榜',
    description: '龙虎榜',
    component: 'ArtDecoMarketData.vue',
    tabs: TAB_CONFIGS['ArtDecoMarketData.vue'] || [],
    requiresAuth: true,
  },
  'market-institution': {
    type: 'monolithic',
    routePath: 'institution',
    title: '机构荐股',
    description: '机构荐股',
    component: 'ArtDecoMarketData.vue',
    tabs: TAB_CONFIGS['ArtDecoMarketData.vue'] || [],
    requiresAuth: true,
  },
  'market-wencai': {
    type: 'monolithic',
    routePath: 'wencai',
    title: '问财选股',
    description: '问财选股',
    component: 'ArtDecoMarketData.vue',
    tabs: TAB_CONFIGS['ArtDecoMarketData.vue'] || [],
    requiresAuth: true,
  },
  'market-screener': {
    type: 'monolithic',
    routePath: 'screener',
    title: '股票筛选',
    description: '股票筛选',
    component: 'ArtDecoStockManagement.vue',
    tabs: TAB_CONFIGS['ArtDecoStockManagement.vue'] || [],
    requiresAuth: true,
  },
  'stock-management': {
    type: 'monolithic',
    routePath: 'management',
    title: '股票管理',
    description: '股票管理',
    component: 'ArtDecoStockManagement.vue',
    tabs: TAB_CONFIGS['ArtDecoStockManagement.vue'] || [],
    requiresAuth: true,
  },
  'stock-portfolio': {
    type: 'monolithic',
    routePath: 'portfolio',
    title: '我的持仓',
    description: '我的持仓',
    component: 'ArtDecoStockManagement.vue',
    tabs: TAB_CONFIGS['ArtDecoStockManagement.vue'] || [],
    requiresAuth: true,
  },
}

// Combined PAGE_CONFIG for backward compatibility
export const PAGE_CONFIG: Record<string, PageConfig> = {
  ...PAGE_CONFIGS,
  ...MONOLITHIC_CONFIGS,
}

// Type guards
export function isRouteName(name: string): name is keyof typeof PAGE_CONFIG {
  return name in PAGE_CONFIG
}

export function isMonolithicConfig(config: PageConfig): config is MonolithicPageConfig {
  return config.type === 'monolithic'
}

export function isStandardConfig(config: PageConfig): config is StandardPageConfig {
  return config.type === 'page'
}

// Helper functions
export function getPageConfig(routeName: string): PageConfig | undefined {
  return PAGE_CONFIG[routeName]
}

export function getTabConfig(routeName: string, tabId: string): TabConfig | undefined {
  const config = PAGE_CONFIG[routeName]
  if (isMonolithicConfig(config)) {
    return config.tabs.find(tab => tab.id === tabId)
  }
  return undefined
}

export function getTabsForComponent(component: string): TabConfig[] {
  return TAB_CONFIGS[component] || []
}

// Export types for external use
export type { PageConfigType, TabConfig, MonolithicPageConfig, StandardPageConfig, PageConfig }
